### ISSUE TITLE
weekly useful materials - 07/05 -

### ISSUE THREAD

**Issue by GENZITSU** [GENZITSU/UsefulMaterials#106]

**Comment by GENZITSU** [comment]
## 全文検索 完全に理解した

全文検索エンジンの仕組みをざっくり理解するための資料。

情報の収集インデックスの作成方法などがざっくり説明されている。

![スクリーンショット 2022-06-29 22 26 08](https://user-images.githubusercontent.com/19774756/176447746-ebd621a2-853c-4c1c-8fa6-2a3ea4a1693c.png)

![スクリーンショット 2022-06-29 22 26 18](https://user-images.githubusercontent.com/19774756/176447772-f19873b8-e24e-48ee-a26e-6998407fddfe.png)

### コメント
メモ

### 出典
[全文検索 完全に理解した](https://speakerdeck.com/segavvy/quan-wen-jian-suo-wan-quan-nili-jie-sita)

**Comment by GENZITSU** [comment]
## sys.path.append() を使わないでください

`sys.path.append()`を用いる弊害と対処法が綴られているブログ。

`sys.path.append()`は楽なのだが、以下のような弊害を生む
1. モジュールへのパスを絶対パスで書いた場合、実行ユーザーごとに修正が必要になる
2. モジュール名を変えた時の修正範囲が大きくなる
3. fake8のコーディング規約に違反している

有望な対処方法は以下

1. poetryのproject.tomlを用いてパッケージを管理する
この管理が一番楽そう
```toml
# from https://qiita.com/siida36/items/b171922546e65b868679#%E8%A7%A3%E6%B1%BA%E6%B3%952-requirementstxt

[tool.poetry]
name = "my_package"
version = "0.1.0"
description = ""
authors = [""]
packages = [
    { include = "my_package", from = "src" }
]
```

2. poetryを使用せずに、setup.pyを記述する

```python
# from https://qiita.com/siida36/items/b171922546e65b868679#%E8%A7%A3%E6%B1%BA%E6%B3%952-requirementstxt

from distutils.core import setup

setup(
    name="my_package",
    version="0.1.0",
    description="",
    author="",
    packages=["my_package"],
    package_dir={
        "my_package": "src/my_package",
    },
    package_data={
        "my_package": [                                                                                                                                      
            "sub_dir/*.py",
        ]
    },
)

```

```
# from https://qiita.com/siida36/items/b171922546e65b868679#%E8%A7%A3%E6%B1%BA%E6%B3%952-requirementstxt

# requirements.txt

-e .
```

### コメント
検証レベルのコードだとsys.path.appendは使いやすくて多用してしまうのだが、アンチパターンであったというのは知らなかった。  
poetry導入を本格的に検討しないとな...

### 出典
[sys.path.append() を使わないでください](https://qiita.com/siida36/items/b171922546e65b868679#%E8%A7%A3%E6%B1%BA%E6%B3%952-requirementstxt)
