### ISSUE TITLE
almost weekly useful materials - 05/31 -

### ISSUE THREAD

**Issue by GENZITSU** [GENZITSU/UsefulMaterials#133]

**Comment by GENZITSU** [comment]
## [PtitPrinceによるPythonでのRaincloud plotの描画](https://oumpy.github.io/blog/2020/12/ptitprince_tutorial.html)

表題の通り

以下のようなRaincloud plotを描画することができる。

![スクリーンショット 2023-05-03 22 29 55](https://user-images.githubusercontent.com/19774756/235930495-74fdff6c-a01e-4008-9b17-99a88b2270bc.png)

### コメント

seabornのviolin plotでも似たような図は書けるけど、ヒストグラムと点が別々に描画されている分こっちの方が見やすいケースもありそう


### 出典
- [PtitPrinceによるPythonでのRaincloud plotの描画](https://oumpy.github.io/blog/2020/12/ptitprince_tutorial.html)
- [PtitPrince](https://github.com/pog87/PtitPrince)

**Comment by GENZITSU** [comment]
## [2023年最新版]Python案件で汎用的に使えるモダンなプロジェクトテンプレート

参考になった部分だけ抜粋

### ディレクトリ構成

```shell
├── .env                    # 環境変数用ファイル（git管理外のため、.env.exampleからコピーする）
├── .env.example            # 環境変数用ファイルのサンプル
├── .env.prd                # 環境変数用ファイルの本番環境用
├── .pre-commit-config.yaml # pre-commit設定ファイル
├── LICENSE.md
├── Makefile                # タスクランナーの定義に使用
├── Readme.md
├── mypy.ini                # mypyの設定ファイル
├── poetry.lock             # poetyrのlockファイル
├── pyproject.toml          # project全体の設定ファイル
├── requirements-dev.txt    # poetryを使用しない場合のrequirements.txt(開発環境用)
├── requirements.txt        # poetryを使用しない場合のrequirements.txt
├── src                     # mainのソースコード
│   ├── common              # 全体で使用する処理をまとめたディレクトリ
│   │   ├── __init__.py
│   │   ├── configs.py      # ソースコード全体で使用する設定の管理
│   │   └── logger.py       # logger管理用
│   ├── logger_config.yaml  # logging設定ファイル
│   ├── main.py             # サンプルのmain
│   └── sub.py              # サンプルのsub関数
└── tests                   # テストコード格納用のディレクトリ
    ├── conftest.py
    └── sub
        ├── __init__.py
        ├── conftest.py
        └── test_sub.py
```

.envはルートディレクトリに配置している。自分は`envs/`下に押し込みそう
`src/common`の中にconfigsとかloggerとかを入れているが、自分は`configs/`をルートに作ってそこに書きそう

### logger configの書き方

```yaml
version: 1
disable_existing_loggers: false

formatters:
  json:
    format: "%(asctime)s %(name)s %(levelname)s  %(message)s %(filename)s %(module)s %(funcName)s %(lineno)d"
    class: pythonjsonlogger.jsonlogger.JsonFormatter
  normal:
    format: "[%(asctime)s - %(levelname)s - %(filename)s(func:%(funcName)s, line:%(lineno)d)] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: normal # json形式にしたい場合はjsonと記述する
    stream: ext://sys.stdout

loggers:
  src:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]
```

ちゃんと仕方書き方がよくわかっていないので、一つの書き方としてメモ。
formatterをjsonと普通の文で切り替え可能にしておくのはなかなか良さそう。

### タスクランナーとしてのMakefile

```
# install
.PHONY: install
install:
	pyenv install 3.10
	poetry env use 3.10
	poetry install
	pre-commit install
```

ちゃんと知らなかったけど `.PHONY`でダミーターゲットを作っているのが味噌っぽい。

### コメント

参考になった。

### 出典
- [[2023年最新版]Python案件で汎用的に使えるモダンなプロジェクトテンプレート](https://zenn.dev/tk_resilie/articles/python_my_best_project)
