### ISSUE TITLE
almost weekly useful materials - 06/28 -

### ISSUE THREAD

**Issue by GENZITSU** [GENZITSU/UsefulMaterials#135]

**Comment by GENZITSU** [comment]
## Docker の healthcheck を初めて使った話

docker compose のdepends_onはコンテナの開始順序のみを制御し、実際にサービスが立ち上がるまで次のサービスの開始を待つわけではない

> depends_on では、 web を開始する前に db と redis の「準備」が整うのを待ちません。単に、順番通り開始するだけです。サービスの準備が調うまで待つ必要がある場合、この問題を解決する方法は [開始順番の制御](https://docs.docker.jp/compose/startup-order.html) をご覧ください。

これを解決するために、confitionとhealthcheckを用いて、サービスが問題なく立ち上がるまで起動を待たせるようにしたとのこと

```yml
# from https://zenn.dev/sun_asterisk/articles/b4b17681d08018

services:
  app:
    depends_on:
      mysql:
        condition: service_healthy   # here
    build: .
    volumes:
      - .:/opt/app/
    ports:
      - 80:3000

  mysql:
    image: mysql:8.0.32-oracle
    env_file:
      - ./.env
    ports:
      - 3306:3306
    healthcheck:   # here
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s

volumes:
  mysql-store:
```

### コメント

実際はここまで明確に開始順序を制御する必要なさそうな気もするけど、知っておいて損はなさそう

### 出典
- [Docker の healthcheck を初めて使った話](https://zenn.dev/sun_asterisk/articles/b4b17681d08018)
